def generate_esp32_firmware(robot, default_speed=50, motor_assignments=None):
    """
    Generates a compilable Arduino (.ino) string for ESP32-S3.

    Motor types per joint:
      - "servo"   → ESP32Servo.h    (1 PWM/LEDC pin)
      - "stepper" → AccelStepper.h  (3 pins: STEP, DIR, EN)

    All pins are allocated from an ESP32-S3 safe GPIO pool.
    A global `used_pins` set guarantees ZERO duplicate pin assignments
    across every joint and every motor type.

    Parameters
    ----------
    robot             : Robot  — model containing joints / joint_relations
    default_speed     : int    — 0-100 % speed (mapped to steps/sec or servo rate)
    motor_assignments : dict   — {joint_name: "servo" | "stepper"}
                                 Missing joints default to "servo".
    """

    # ─────────────────────────────────────────────────────────────────────────
    # ESP32-S3 Safe GPIO Pool
    # Excluded: 0,3,45,46 (strapping) | 19,20 (USB-OTG) | 26-37 (Flash/PSRAM)
    # Kept:     1, 2, 4–18, 21, 38, 39, 40, 41, 42, 43, 44, 47, 48
    # Order: prefer mid-range digital-capable pins first, USB-adjacent last.
    # ─────────────────────────────────────────────────────────────────────────
    _GPIO_POOL = [
        4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        21,
        38, 43, 44, 47, 48,
        1, 2,
        39, 40, 41, 42,   # JTAG — safe to use if not debugging
    ]

    # ─────────────────────────────────────────────────────────────────────────
    # Stepper motion constants
    # NEMA17 @ 200 steps/rev × DRV8825 ×16 micro-step = 3200 steps/rev
    # STEPS_PER_DEG = 3200 / 360 ≈ 8.8889
    # ─────────────────────────────────────────────────────────────────────────
    STEPS_PER_REV   = 200
    MICROSTEP        = 16
    STEPS_PER_DEG   = round((STEPS_PER_REV * MICROSTEP) / 360.0, 4)   # 8.8889
    MAX_SPEED_SPS   = 3200    # steps / second  (full speed = 1 rev/sec)
    ACCEL_SPS2      = 1600    # steps / second²

    # ─────────────────────────────────────────────────────────────────────────
    # Build ordered list of independent joints (exclude slave joints)
    # ─────────────────────────────────────────────────────────────────────────
    slave_ids = set()
    for slaves in robot.joint_relations.values():
        for s_id, _ in slaves:
            slave_ids.add(s_id)

    joint_names = [n for n in robot.joints if n not in slave_ids]

    if motor_assignments is None:
        motor_assignments = {}

    # ─────────────────────────────────────────────────────────────────────────
    # Pin allocator — one shared pool, no duplicates guaranteed
    # ─────────────────────────────────────────────────────────────────────────
    _available = list(_GPIO_POOL)   # copy so we can pop
    _used       = set()

    def _alloc_pin():
        """Pull the next unused safe GPIO from the pool. Returns -1 if exhausted."""
        for pin in _available:
            if pin not in _used:
                _used.add(pin)
                return pin
        return -1   # pool exhausted

    # ─────────────────────────────────────────────────────────────────────────
    # Assign pins per joint
    # ─────────────────────────────────────────────────────────────────────────
    servo_joints   = []   # [(name, joint_obj, pwm_pin)]
    stepper_joints = []   # [(name, joint_obj, step_pin, dir_pin, en_pin)]

    for name in joint_names:
        jobj  = robot.joints[name]
        mtype = motor_assignments.get(name, "servo").lower()

        if mtype == "stepper":
            step = _alloc_pin()
            dir_ = _alloc_pin()
            en   = _alloc_pin()
            stepper_joints.append((name, jobj, step, dir_, en))
        else:
            pwm = _alloc_pin()
            servo_joints.append((name, jobj, pwm))

    num_servo   = len(servo_joints)
    num_stepper = len(stepper_joints)
    need_servo_lib   = num_servo   > 0
    need_stepper_lib = num_stepper > 0

    # ─────────────────────────────────────────────────────────────────────────
    # Build pin-assignment reference table for the header comment
    # ─────────────────────────────────────────────────────────────────────────
    pin_table = []
    for name, jobj, pwm in servo_joints:
        pin_table.append((name, "SERVO",   f"PWM={pwm}"))
    for name, jobj, step, dir_, en in stepper_joints:
        pin_table.append((name, "STEPPER", f"STEP={step}, DIR={dir_}, EN={en}"))

    # ─────────────────────────────────────────────────────────────────────────
    # Code Generation
    # ─────────────────────────────────────────────────────────────────────────
    c = []

    # ── File header ───────────────────────────────────────────────────────────
    c.append("/**")
    c.append(" * ╔══════════════════════════════════════════════════════╗")
    c.append(" * ║        ToRoTRoN — ESP32-S3 Robot Firmware           ║")
    c.append(" * ║       Auto-generated by ToRoTRoN Desktop App        ║")
    c.append(" * ╚══════════════════════════════════════════════════════╝")
    c.append(" *")
    c.append(" *  Target MCU  : ESP32-S3")
    c.append(" *  Libraries   : ESP32Servo (≥0.13), AccelStepper (≥1.64)")
    c.append(" *  Protocol    : Serial 115200 baud")
    c.append(" *  Command fmt : \"<joint_name>:<angle_deg>:<speed_pct>\\n\"")
    c.append(" *                angle_deg  — float, robot degrees (0 = home)")
    c.append(" *                speed_pct  — float, 0-100 %")
    c.append(" *")
    c.append(f" *  Joints ({len(joint_names)} independent):")
    max_name = max((len(n) for n in joint_names), default=10)
    for name, mtype, pins in pin_table:
        c.append(f" *    {name:<{max_name}}  {mtype:<8}  {pins}")
    c.append(" *")
    if need_stepper_lib:
        c.append(f" *  Stepper config : {STEPS_PER_REV} steps/rev × ×{MICROSTEP} micro-step")
        c.append(f" *                   {STEPS_PER_DEG} steps/degree")
        c.append(f" *                   Max speed: {MAX_SPEED_SPS} steps/s")
    c.append(" */")
    c.append("")

    # ── Board guard ───────────────────────────────────────────────────────────
    c.append("#if !defined(CONFIG_IDF_TARGET_ESP32S3)")
    c.append("  #error \"This firmware is generated for ESP32-S3 only. \"")
    c.append("         \"Re-generate for your target board.\"")
    c.append("#endif")
    c.append("")

    # ── Includes ──────────────────────────────────────────────────────────────
    if need_servo_lib:
        c.append("#include <ESP32Servo.h>")
    if need_stepper_lib:
        c.append("#include <AccelStepper.h>")
    c.append("")

    # ── Stepper constants ─────────────────────────────────────────────────────
    if need_stepper_lib:
        c.append("// ── Stepper motion constants ───────────────────────────────")
        c.append(f"#define STEPS_PER_DEG  {STEPS_PER_DEG}f")
        c.append(f"#define MAX_SPEED_SPS  {MAX_SPEED_SPS}.0f")
        c.append(f"#define ACCEL_SPS2     {ACCEL_SPS2}.0f")
        c.append("")

    # ── Joint counts ──────────────────────────────────────────────────────────
    c.append(f"#define NUM_SERVO_JOINTS   {num_servo}")
    c.append(f"#define NUM_STEPPER_JOINTS {num_stepper}")
    c.append("")

    # ── Servo struct ──────────────────────────────────────────────────────────
    if need_servo_lib:
        c.append("// ── Servo joints ───────────────────────────────────────────")
        c.append("struct ServoJoint {")
        c.append("  Servo  servo;")
        c.append("  const char* name;")
        c.append("  float  current_deg;   // current interpolated angle")
        c.append("  float  target_deg;    // commanded target angle")
        c.append("  float  speed_pct;     // 0-100, controls slew rate")
        c.append("  int    pin;")
        c.append("  float  min_limit;     // joint software limit (deg)")
        c.append("  float  max_limit;")
        c.append("};")
        c.append("")
        c.append("ServoJoint sJoints[NUM_SERVO_JOINTS];")
        c.append("")

    # ── Stepper struct ────────────────────────────────────────────────────────
    if need_stepper_lib:
        c.append("// ── Stepper joints ─────────────────────────────────────────")
        c.append("struct StepperJoint {")
        c.append("  AccelStepper stepper;")
        c.append("  const char*  name;")
        c.append("  float        target_deg;")
        c.append("  float        speed_pct;")
        c.append("  int          step_pin;")
        c.append("  int          dir_pin;")
        c.append("  int          en_pin;")
        c.append("  float        min_limit;")
        c.append("  float        max_limit;")
        c.append("};")
        c.append("")
        # Declare globals filled in setup()
        c.append("// AccelStepper cannot be aggregate-initialised; initialise in setup()")
        c.append("AccelStepper _rawSteppers[NUM_STEPPER_JOINTS] = {")
        for i, (name, jobj, step, dir_, en) in enumerate(stepper_joints):
            comma = "," if i < num_stepper - 1 else ""
            c.append(f"  AccelStepper(AccelStepper::DRIVER, {step}, {dir_}){comma}  // {name}")
        c.append("};")
        c.append("StepperJoint stJoints[NUM_STEPPER_JOINTS];")
        c.append("")

    # ── setup() ───────────────────────────────────────────────────────────────
    c.append("// ═══════════════════════════════════════════════════════════════")
    c.append("void setup() {")
    c.append("  Serial.begin(115200);")
    c.append("  delay(300);")
    c.append("  Serial.println(\"\\n--- ToRoTRoN ESP32-S3 BOOTING ---\");")
    c.append("")

    if need_servo_lib:
        c.append("  // Allocate LEDC timer channels for ESP32Servo")
        c.append("  ESP32PWM::allocateTimer(0);")
        c.append("  ESP32PWM::allocateTimer(1);")
        c.append("  ESP32PWM::allocateTimer(2);")
        c.append("  ESP32PWM::allocateTimer(3);")
        c.append("")

    # Init each servo joint
    for i, (name, jobj, pwm) in enumerate(servo_joints):
        mn = float(getattr(jobj, 'min_limit', -90))
        mx = float(getattr(jobj, 'max_limit',  90))
        home_deg = 0.0   # robot home position maps to servo 90°
        home_srv = int(max(0, min(180, home_deg + 90)))
        c.append(f"  // ── Servo [{i}]: {name}  (GPIO {pwm})")
        c.append(f"  sJoints[{i}].name        = \"{name}\";")
        c.append(f"  sJoints[{i}].pin         = {pwm};")
        c.append(f"  sJoints[{i}].current_deg = 0.0f;")
        c.append(f"  sJoints[{i}].target_deg  = 0.0f;")
        c.append(f"  sJoints[{i}].speed_pct   = {default_speed}.0f;")
        c.append(f"  sJoints[{i}].min_limit   = {mn}f;")
        c.append(f"  sJoints[{i}].max_limit   = {mx}f;")
        if pwm != -1:
            c.append(f"  sJoints[{i}].servo.setPeriodHertz(50);          // Standard 50 Hz PWM")
            c.append(f"  sJoints[{i}].servo.attach({pwm}, 500, 2400);    // 500-2400 µs pulse range")
            c.append(f"  sJoints[{i}].servo.write({home_srv});           // Move to home position")
        else:
            c.append(f"  // WARNING: No GPIO available for {name}. Check pool size.")
        c.append("")

    # Init each stepper joint
    for i, (name, jobj, step, dir_, en) in enumerate(stepper_joints):
        mn = float(getattr(jobj, 'min_limit', -180))
        mx = float(getattr(jobj, 'max_limit',  180))
        c.append(f"  // ── Stepper [{i}]: {name}  (STEP={step}, DIR={dir_}, EN={en})")
        c.append(f"  stJoints[{i}].stepper    = _rawSteppers[{i}];")
        c.append(f"  stJoints[{i}].name       = \"{name}\";")
        c.append(f"  stJoints[{i}].target_deg = 0.0f;")
        c.append(f"  stJoints[{i}].speed_pct  = {default_speed}.0f;")
        c.append(f"  stJoints[{i}].step_pin   = {step};")
        c.append(f"  stJoints[{i}].dir_pin    = {dir_};")
        c.append(f"  stJoints[{i}].en_pin     = {en};")
        c.append(f"  stJoints[{i}].min_limit  = {mn}f;")
        c.append(f"  stJoints[{i}].max_limit  = {mx}f;")
        if en != -1:
            c.append(f"  pinMode({en}, OUTPUT);")
            c.append(f"  digitalWrite({en}, LOW);                         // Enable driver (active LOW)")
        c.append(f"  stJoints[{i}].stepper.setMaxSpeed(MAX_SPEED_SPS);")
        c.append(f"  stJoints[{i}].stepper.setAcceleration(ACCEL_SPS2);")
        c.append(f"  stJoints[{i}].stepper.setCurrentPosition(0);        // Home = 0 steps")
        c.append("")

    c.append("  Serial.println(\"--- HARDWARE ONLINE --- Starting handshake...\");")
    c.append("  performHandshake();")
    c.append("}")
    c.append("")

    # ── performHandshake() ────────────────────────────────────────────────────
    c.append("// ═══════════════════════════════════════════════════════════════")
    c.append("void performHandshake() {")
    if need_servo_lib:
        c.append("  // Servo joints: nudge +10° then return to home")
        c.append("  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {")
        c.append("    if (sJoints[i].pin == -1) continue;")
        c.append("    sJoints[i].servo.write(constrain((int)(sJoints[i].current_deg + 90 + 10), 0, 180));")
        c.append("  }")
        c.append("  delay(400);")
        c.append("  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {")
        c.append("    if (sJoints[i].pin == -1) continue;")
        c.append("    sJoints[i].servo.write(90); // return to home")
        c.append("  }")
        c.append("  delay(300);")

    if need_stepper_lib:
        c.append("  // Stepper joints: nudge 3° forward and back to confirm wiring")
        c.append("  long nudge = (long)(3.0f * STEPS_PER_DEG);")
        c.append("  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {")
        c.append("    stJoints[i].stepper.moveTo(nudge);")
        c.append("    for (int k = 0; k < 50; k++) { stJoints[i].stepper.run(); delay(8); }")
        c.append("    stJoints[i].stepper.moveTo(0);")
        c.append("    for (int k = 0; k < 50; k++) { stJoints[i].stepper.run(); delay(8); }")
        c.append("  }")

    c.append("  Serial.println(\"HANDSHAKE OK — Robot ready.\");")
    c.append("}")
    c.append("")

    # ── loop() ────────────────────────────────────────────────────────────────
    c.append("// ═══════════════════════════════════════════════════════════════")
    c.append("void loop() {")
    c.append("  updateSerial();")
    if need_servo_lib:
        c.append("  updateServos();")
    if need_stepper_lib:
        c.append("  updateSteppers();   // Must run every loop — non-blocking")
    c.append("  delay(8);             // ~125 Hz control loop")
    c.append("}")
    c.append("")

    # ── updateSerial() ─────────────────────────────────────────────────────────
    c.append("// ═══════════════════════════════════════════════════════════════")
    c.append("void updateSerial() {")
    c.append("  while (Serial.available() > 0) {")
    c.append("    String cmd = Serial.readStringUntil('\\n');")
    c.append("    cmd.trim();")
    c.append("    if (cmd.length() == 0) continue;")
    c.append("    if (cmd == \"?\")    { Serial.println(\"PONG\"); continue; }")
    c.append("    if (cmd == \"HOME\") { goHome(); continue; }")
    c.append("    parseCommand(cmd);")
    c.append("  }")
    c.append("}")
    c.append("")

    # ── parseCommand() ─────────────────────────────────────────────────────────
    c.append("// ═══════════════════════════════════════════════════════════════")
    c.append("// Command format: \"<name>:<angle_deg>:<speed_pct>\"")
    c.append("void parseCommand(const String& cmd) {")
    c.append("  int first = cmd.indexOf(':');")
    c.append("  int last  = cmd.lastIndexOf(':');")
    c.append("  if (first < 1 || last <= first) {")
    c.append("    Serial.print(\"ERR: Malformed cmd: \"); Serial.println(cmd);")
    c.append("    return;")
    c.append("  }")
    c.append("")
    c.append("  String name  = cmd.substring(0, first);")
    c.append("  float  angle = cmd.substring(first + 1, last).toFloat();")
    c.append("  float  spd   = cmd.substring(last  + 1).toFloat();")
    c.append("")

    if need_servo_lib:
        c.append("  // Search servo joints")
        c.append("  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {")
        c.append("    if (name.equalsIgnoreCase(sJoints[i].name)) {")
        c.append("      // Clamp to joint software limits")
        c.append("      angle = constrain(angle, sJoints[i].min_limit, sJoints[i].max_limit);")
        c.append("      sJoints[i].target_deg = angle;")
        c.append("      sJoints[i].speed_pct  = constrain(spd, 0.0f, 100.0f);")
        c.append("      Serial.print(\"ACK[SERVO] \"); Serial.print(sJoints[i].name);")
        c.append("      Serial.print(\" -> \"); Serial.print(angle); Serial.println(\" deg\");")
        c.append("      return;")
        c.append("    }")
        c.append("  }")
        c.append("")

    if need_stepper_lib:
        c.append("  // Search stepper joints")
        c.append("  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {")
        c.append("    if (name.equalsIgnoreCase(stJoints[i].name)) {")
        c.append("      angle = constrain(angle, stJoints[i].min_limit, stJoints[i].max_limit);")
        c.append("      stJoints[i].target_deg = angle;")
        c.append("      stJoints[i].speed_pct  = constrain(spd, 0.0f, 100.0f);")
        c.append("      long   steps   = (long)(angle * STEPS_PER_DEG);")
        c.append("      float  sps     = (stJoints[i].speed_pct / 100.0f) * MAX_SPEED_SPS;")
        c.append("      if (sps < 50.0f) sps = 50.0f;  // minimum speed guard")
        c.append("      stJoints[i].stepper.setMaxSpeed(sps);")
        c.append("      stJoints[i].stepper.moveTo(steps);")
        c.append("      Serial.print(\"ACK[STEP] \"); Serial.print(stJoints[i].name);")
        c.append("      Serial.print(\" -> \"); Serial.print(angle);")
        c.append("      Serial.print(\" deg | \"); Serial.print(steps);")
        c.append("      Serial.println(\" steps\");")
        c.append("      return;")
        c.append("    }")
        c.append("  }")
        c.append("")

    c.append("  Serial.print(\"ERR: Unknown joint '\"); Serial.print(name); Serial.println(\"'\");")
    c.append("}")
    c.append("")

    # ── goHome() ──────────────────────────────────────────────────────────────
    c.append("// ═══════════════════════════════════════════════════════════════")
    c.append("// Move all joints to home (0 degrees)")
    c.append("void goHome() {")
    if need_servo_lib:
        c.append("  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {")
        c.append("    sJoints[i].target_deg = 0.0f;")
        c.append("  }")
    if need_stepper_lib:
        c.append("  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {")
        c.append("    stJoints[i].target_deg = 0.0f;")
        c.append("    float home_sps = (stJoints[i].speed_pct / 100.0f) * MAX_SPEED_SPS;")
        c.append("    if (home_sps < 50.0f) home_sps = 50.0f;")
        c.append("    stJoints[i].stepper.setMaxSpeed(home_sps);")
        c.append("    stJoints[i].stepper.moveTo(0);")
        c.append("  }")
    c.append("  Serial.println(\"HOME: All joints returning to 0 deg.\");")
    c.append("}")
    c.append("")

    # ── updateServos() ─────────────────────────────────────────────────────────
    if need_servo_lib:
        c.append("// ═══════════════════════════════════════════════════════════════")
        c.append("// Smooth servo interpolation (runs every 8 ms)")
        c.append("void updateServos() {")
        c.append("  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {")
        c.append("    if (sJoints[i].pin == -1) continue;")
        c.append("    float cur = sJoints[i].current_deg;")
        c.append("    float tgt = sJoints[i].target_deg;")
        c.append("    float err = tgt - cur;")
        c.append("    if (fabsf(err) < 0.1f) {")
        c.append("      sJoints[i].current_deg = tgt;        // snap to target")
        c.append("    } else {")
        c.append("      // Speed_pct ∈ [0,100] → step ∈ [0.08, 8] deg per tick")
        c.append("      float step = (sJoints[i].speed_pct / 100.0f) * 8.0f;")
        c.append("      if (step < 0.08f) step = 0.08f;")
        c.append("      sJoints[i].current_deg += (err > 0) ? step : -step;")
        c.append("      // Overshoot guard")
        c.append("      if ((err > 0 && sJoints[i].current_deg > tgt) ||")
        c.append("          (err < 0 && sJoints[i].current_deg < tgt))")
        c.append("        sJoints[i].current_deg = tgt;")
        c.append("    }")
        c.append("    // Map robot degrees [-180,+180] → servo [0,180]")
        c.append("    //   robot 0° → servo 90° (midpoint)")
        c.append("    int sv = (int)constrain(sJoints[i].current_deg + 90.0f, 0.0f, 180.0f);")
        c.append("    sJoints[i].servo.write(sv);")
        c.append("  }")
        c.append("}")
        c.append("")

    # ── updateSteppers() ───────────────────────────────────────────────────────
    if need_stepper_lib:
        c.append("// ═══════════════════════════════════════════════════════════════")
        c.append("// Non-blocking AccelStepper tick — MUST be called every loop iter")
        c.append("void updateSteppers() {")
        c.append("  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {")
        c.append("    stJoints[i].stepper.run();")
        c.append("  }")
        c.append("}")
        c.append("")

    return "\n".join(c)
