/**
 * ╔══════════════════════════════════════════════════════╗
 * ║        ToRoTRoN — ESP32-S3 Robot Firmware           ║
 * ║       Auto-generated by ToRoTRoN Desktop App        ║
 * ╚══════════════════════════════════════════════════════╝
 *
 *  Target MCU  : ESP32-S3
 *  Libraries   : ESP32Servo (≥0.13), AccelStepper (≥1.64)
 *  Protocol    : Serial 115200 baud
 *  Command fmt : "<joint_name>:<angle_deg>:<speed_pct>\n"
 *                angle_deg  — float, robot degrees (0 = home)
 *                speed_pct  — float, 0-100 %
 *
 *  Joints (6 independent):
 *    j1  SERVO     PWM=4
 *    j2  SERVO     PWM=5
 *    j3  SERVO     PWM=6
 *    j4  SERVO     PWM=7
 *    j5  SERVO     PWM=8
 *    j6  SERVO     PWM=9
 *
 */

#if !defined(CONFIG_IDF_TARGET_ESP32S3)
  #error "This firmware is generated for ESP32-S3 only. "
         "Re-generate for your target board."
#endif

#include <ESP32Servo.h>

#define NUM_SERVO_JOINTS   6
#define NUM_STEPPER_JOINTS 0
#define SERIAL_LINE_BUF    96
#define CONTROL_PERIOD_MS  8

// ── Servo joints ───────────────────────────────────────────
struct ServoJoint {
  Servo  servo;
  const char* name;
  float  current_deg;   // current interpolated angle
  float  target_deg;    // commanded target angle
  float  speed_pct;     // 0-100, controls slew rate
  int    pin;
  float  min_limit;     // joint software limit (deg)
  float  max_limit;
};

ServoJoint sJoints[NUM_SERVO_JOINTS];

char serialLine[SERIAL_LINE_BUF];
uint8_t serialLinePos = 0;
unsigned long lastControlTick = 0;

// ═══════════════════════════════════════════════════════════════
void setup() {
  Serial.begin(115200);
  delay(300);
  Serial.println("\n--- ToRoTRoN ESP32-S3 BOOTING ---");
  Serial.println("BOOT:ESP32-S3");

  // Allocate LEDC timer channels for ESP32Servo
  ESP32PWM::allocateTimer(0);
  ESP32PWM::allocateTimer(1);
  ESP32PWM::allocateTimer(2);
  ESP32PWM::allocateTimer(3);

  // ── Servo [0]: j1  (GPIO 4)
  sJoints[0].name        = "j1";
  sJoints[0].pin         = 4;
  sJoints[0].current_deg = 0.0f;
  sJoints[0].target_deg  = 0.0f;
  sJoints[0].speed_pct   = 50.0f;
  sJoints[0].min_limit   = -180.0f;
  sJoints[0].max_limit   = 180.0f;
  sJoints[0].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[0].servo.attach(4, 500, 2400);    // 500-2400 µs pulse range
  sJoints[0].servo.write(90);           // Move to home position

  // ── Servo [1]: j2  (GPIO 5)
  sJoints[1].name        = "j2";
  sJoints[1].pin         = 5;
  sJoints[1].current_deg = 0.0f;
  sJoints[1].target_deg  = 0.0f;
  sJoints[1].speed_pct   = 50.0f;
  sJoints[1].min_limit   = -90.0f;
  sJoints[1].max_limit   = 90.0f;
  sJoints[1].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[1].servo.attach(5, 500, 2400);    // 500-2400 µs pulse range
  sJoints[1].servo.write(90);           // Move to home position

  // ── Servo [2]: j3  (GPIO 6)
  sJoints[2].name        = "j3";
  sJoints[2].pin         = 6;
  sJoints[2].current_deg = 0.0f;
  sJoints[2].target_deg  = 0.0f;
  sJoints[2].speed_pct   = 50.0f;
  sJoints[2].min_limit   = -90.0f;
  sJoints[2].max_limit   = 90.0f;
  sJoints[2].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[2].servo.attach(6, 500, 2400);    // 500-2400 µs pulse range
  sJoints[2].servo.write(90);           // Move to home position

  // ── Servo [3]: j4  (GPIO 7)
  sJoints[3].name        = "j4";
  sJoints[3].pin         = 7;
  sJoints[3].current_deg = 0.0f;
  sJoints[3].target_deg  = 0.0f;
  sJoints[3].speed_pct   = 50.0f;
  sJoints[3].min_limit   = -180.0f;
  sJoints[3].max_limit   = 180.0f;
  sJoints[3].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[3].servo.attach(7, 500, 2400);    // 500-2400 µs pulse range
  sJoints[3].servo.write(90);           // Move to home position

  // ── Servo [4]: j5  (GPIO 8)
  sJoints[4].name        = "j5";
  sJoints[4].pin         = 8;
  sJoints[4].current_deg = 0.0f;
  sJoints[4].target_deg  = 0.0f;
  sJoints[4].speed_pct   = 50.0f;
  sJoints[4].min_limit   = -180.0f;
  sJoints[4].max_limit   = 180.0f;
  sJoints[4].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[4].servo.attach(8, 500, 2400);    // 500-2400 µs pulse range
  sJoints[4].servo.write(90);           // Move to home position

  // ── Servo [5]: j6  (GPIO 9)
  sJoints[5].name        = "j6";
  sJoints[5].pin         = 9;
  sJoints[5].current_deg = 0.0f;
  sJoints[5].target_deg  = 0.0f;
  sJoints[5].speed_pct   = 50.0f;
  sJoints[5].min_limit   = 0.0f;
  sJoints[5].max_limit   = 45.0f;
  sJoints[5].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[5].servo.attach(9, 500, 2400);    // 500-2400 µs pulse range
  sJoints[5].servo.write(90);           // Move to home position

  Serial.println("--- HARDWARE ONLINE --- Starting handshake...");
  performHandshake();
  Serial.println("READY");
}

// ═══════════════════════════════════════════════════════════════
void performHandshake() {
  // Servo joints: nudge +10° then return to home
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (sJoints[i].pin == -1) continue;
    sJoints[i].servo.write(constrain((int)(sJoints[i].current_deg + 90 + 10), 0, 180));
  }
  delay(400);
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (sJoints[i].pin == -1) continue;
    sJoints[i].servo.write(90); // return to home
  }
  delay(300);
  Serial.println("HANDSHAKE OK — Robot ready.");
}

// ═══════════════════════════════════════════════════════════════
void loop() {
  updateSerial();

  unsigned long now = millis();
  if ((now - lastControlTick) >= CONTROL_PERIOD_MS) {
    lastControlTick = now;
    updateServos();
  }
}

// ═══════════════════════════════════════════════════════════════
void updateSerial() {
  while (Serial.available() > 0) {
    char c = (char)Serial.read();
    if (c == '\r') continue;
    if (c == '\n') {
      serialLine[serialLinePos] = '\0';
      String cmd = String(serialLine);
      cmd.trim();
      serialLinePos = 0;
      if (cmd.length() == 0) continue;
      if (cmd == "?" || cmd == "PING") { Serial.println("PONG"); continue; }
      if (cmd == "HOME") { goHome(); continue; }
      parseCommand(cmd);
      continue;
    }

    if (serialLinePos < (SERIAL_LINE_BUF - 1)) {
      serialLine[serialLinePos++] = c;
    } else {
      serialLinePos = 0;
      Serial.println("ERR: RX overflow");
    }
  }
}

// ═══════════════════════════════════════════════════════════════
// Command format: "<name>:<angle_deg>:<speed_pct>"
void parseCommand(const String& cmd) {
  int first = cmd.indexOf(':');
  int last  = cmd.lastIndexOf(':');
  if (first < 1 || last <= first) {
    Serial.print("ERR: Malformed cmd: "); Serial.println(cmd);
    return;
  }

  String name  = cmd.substring(0, first);
  float  angle = cmd.substring(first + 1, last).toFloat();
  float  spd   = cmd.substring(last  + 1).toFloat();

  // Search servo joints
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (name.equalsIgnoreCase(sJoints[i].name)) {
      // Clamp to joint software limits
      angle = constrain(angle, sJoints[i].min_limit, sJoints[i].max_limit);
      sJoints[i].target_deg = angle;
      sJoints[i].speed_pct  = constrain(spd, 0.0f, 100.0f);
      Serial.print("ACK:"); Serial.print(sJoints[i].name);
      Serial.print(":SERVO:"); Serial.print(angle, 2);
      Serial.print(":"); Serial.println(sJoints[i].speed_pct, 2);
      return;
    }
  }

  Serial.print("ERR: Unknown joint '"); Serial.print(name); Serial.println("'");
}

// ═══════════════════════════════════════════════════════════════
// Move all joints to home (0 degrees)
void goHome() {
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    sJoints[i].target_deg = 0.0f;
  }
  Serial.println("HOME: All joints returning to 0 deg.");
}

// ═══════════════════════════════════════════════════════════════
// Smooth servo interpolation (runs every 8 ms)
void updateServos() {
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (sJoints[i].pin == -1) continue;
    float cur = sJoints[i].current_deg;
    float tgt = sJoints[i].target_deg;
    float err = tgt - cur;
    if (fabsf(err) < 0.1f) {
      sJoints[i].current_deg = tgt;        // snap to target
    } else {
      // Speed_pct ∈ [0,100] → step ∈ [0.05, 4.5] deg per control tick
      float step = (sJoints[i].speed_pct / 100.0f) * 4.5f;
      if (step < 0.08f) step = 0.08f;
      sJoints[i].current_deg += (err > 0) ? step : -step;
      // Overshoot guard
      if ((err > 0 && sJoints[i].current_deg > tgt) ||
          (err < 0 && sJoints[i].current_deg < tgt))
        sJoints[i].current_deg = tgt;
    }
    // Map robot degrees [-180,+180] → servo [0,180]
    //   robot 0° → servo 90° (midpoint)
    int sv = (int)constrain(sJoints[i].current_deg + 90.0f, 0.0f, 180.0f);
    sJoints[i].servo.write(sv);
  }
}
