/**
 * ╔══════════════════════════════════════════════════════╗
 * ║        ToRoTRoN — ESP32-S3 Robot Firmware           ║
 * ║       Auto-generated by ToRoTRoN Desktop App        ║
 * ╚══════════════════════════════════════════════════════╝
 *
 *  Target MCU  : ESP32-S3
 *  Libraries   : ESP32Servo (≥0.13), AccelStepper (≥1.64)
 *  Protocol    : Serial 115200 baud
 *  Command fmt : "<joint_name>:<angle_deg>:<speed_pct>\n"
 *                angle_deg  — float, robot degrees (0 = home)
 *                speed_pct  — float, 0-100 %
 *
 *  Joints (6 independent):
 *    j1  SERVO     PWM=4
 *    j4  SERVO     PWM=11
 *    j5  SERVO     PWM=12
 *    j6  SERVO     PWM=13
 *    j2  STEPPER   STEP=5, DIR=6, EN=7
 *    j3  STEPPER   STEP=8, DIR=9, EN=10
 *
 *  Stepper config : 200 steps/rev × ×16 micro-step
 *                   8.8889 steps/degree
 *                   Max speed: 3200 steps/s
 */

#if !defined(CONFIG_IDF_TARGET_ESP32S3)
  #error "This firmware is generated for ESP32-S3 only. "
         "Re-generate for your target board."
#endif

#include <ESP32Servo.h>
#include <AccelStepper.h>

// ── Stepper motion constants ───────────────────────────────
#define STEPS_PER_DEG  8.8889f
#define MAX_SPEED_SPS  3200.0f
#define ACCEL_SPS2     1600.0f

#define NUM_SERVO_JOINTS   4
#define NUM_STEPPER_JOINTS 2

// ── Servo joints ───────────────────────────────────────────
struct ServoJoint {
  Servo  servo;
  const char* name;
  float  current_deg;   // current interpolated angle
  float  target_deg;    // commanded target angle
  float  speed_pct;     // 0-100, controls slew rate
  int    pin;
  float  min_limit;     // joint software limit (deg)
  float  max_limit;
};

ServoJoint sJoints[NUM_SERVO_JOINTS];

// ── Stepper joints ─────────────────────────────────────────
struct StepperJoint {
  AccelStepper stepper;
  const char*  name;
  float        target_deg;
  float        speed_pct;
  int          step_pin;
  int          dir_pin;
  int          en_pin;
  float        min_limit;
  float        max_limit;
};

// AccelStepper cannot be aggregate-initialised; initialise in setup()
AccelStepper _rawSteppers[NUM_STEPPER_JOINTS] = {
  AccelStepper(AccelStepper::DRIVER, 5, 6),  // j2
  AccelStepper(AccelStepper::DRIVER, 8, 9)  // j3
};
StepperJoint stJoints[NUM_STEPPER_JOINTS];

// ═══════════════════════════════════════════════════════════════
void setup() {
  Serial.begin(115200);
  delay(300);
  Serial.println("\n--- ToRoTRoN ESP32-S3 BOOTING ---");

  // Allocate LEDC timer channels for ESP32Servo
  ESP32PWM::allocateTimer(0);
  ESP32PWM::allocateTimer(1);
  ESP32PWM::allocateTimer(2);
  ESP32PWM::allocateTimer(3);

  // ── Servo [0]: j1  (GPIO 4)
  sJoints[0].name        = "j1";
  sJoints[0].pin         = 4;
  sJoints[0].current_deg = 0.0f;
  sJoints[0].target_deg  = 0.0f;
  sJoints[0].speed_pct   = 50.0f;
  sJoints[0].min_limit   = -180.0f;
  sJoints[0].max_limit   = 180.0f;
  sJoints[0].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[0].servo.attach(4, 500, 2400);    // 500-2400 µs pulse range
  sJoints[0].servo.write(90);           // Move to home position

  // ── Servo [1]: j4  (GPIO 11)
  sJoints[1].name        = "j4";
  sJoints[1].pin         = 11;
  sJoints[1].current_deg = 0.0f;
  sJoints[1].target_deg  = 0.0f;
  sJoints[1].speed_pct   = 50.0f;
  sJoints[1].min_limit   = -180.0f;
  sJoints[1].max_limit   = 180.0f;
  sJoints[1].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[1].servo.attach(11, 500, 2400);    // 500-2400 µs pulse range
  sJoints[1].servo.write(90);           // Move to home position

  // ── Servo [2]: j5  (GPIO 12)
  sJoints[2].name        = "j5";
  sJoints[2].pin         = 12;
  sJoints[2].current_deg = 0.0f;
  sJoints[2].target_deg  = 0.0f;
  sJoints[2].speed_pct   = 50.0f;
  sJoints[2].min_limit   = -180.0f;
  sJoints[2].max_limit   = 180.0f;
  sJoints[2].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[2].servo.attach(12, 500, 2400);    // 500-2400 µs pulse range
  sJoints[2].servo.write(90);           // Move to home position

  // ── Servo [3]: j6  (GPIO 13)
  sJoints[3].name        = "j6";
  sJoints[3].pin         = 13;
  sJoints[3].current_deg = 0.0f;
  sJoints[3].target_deg  = 0.0f;
  sJoints[3].speed_pct   = 50.0f;
  sJoints[3].min_limit   = 0.0f;
  sJoints[3].max_limit   = 45.0f;
  sJoints[3].servo.setPeriodHertz(50);          // Standard 50 Hz PWM
  sJoints[3].servo.attach(13, 500, 2400);    // 500-2400 µs pulse range
  sJoints[3].servo.write(90);           // Move to home position

  // ── Stepper [0]: j2  (STEP=5, DIR=6, EN=7)
  stJoints[0].stepper    = _rawSteppers[0];
  stJoints[0].name       = "j2";
  stJoints[0].target_deg = 0.0f;
  stJoints[0].speed_pct  = 50.0f;
  stJoints[0].step_pin   = 5;
  stJoints[0].dir_pin    = 6;
  stJoints[0].en_pin     = 7;
  stJoints[0].min_limit  = -90.0f;
  stJoints[0].max_limit  = 90.0f;
  pinMode(7, OUTPUT);
  digitalWrite(7, LOW);                         // Enable driver (active LOW)
  stJoints[0].stepper.setMaxSpeed(MAX_SPEED_SPS);
  stJoints[0].stepper.setAcceleration(ACCEL_SPS2);
  stJoints[0].stepper.setCurrentPosition(0);        // Home = 0 steps

  // ── Stepper [1]: j3  (STEP=8, DIR=9, EN=10)
  stJoints[1].stepper    = _rawSteppers[1];
  stJoints[1].name       = "j3";
  stJoints[1].target_deg = 0.0f;
  stJoints[1].speed_pct  = 50.0f;
  stJoints[1].step_pin   = 8;
  stJoints[1].dir_pin    = 9;
  stJoints[1].en_pin     = 10;
  stJoints[1].min_limit  = -90.0f;
  stJoints[1].max_limit  = 90.0f;
  pinMode(10, OUTPUT);
  digitalWrite(10, LOW);                         // Enable driver (active LOW)
  stJoints[1].stepper.setMaxSpeed(MAX_SPEED_SPS);
  stJoints[1].stepper.setAcceleration(ACCEL_SPS2);
  stJoints[1].stepper.setCurrentPosition(0);        // Home = 0 steps

  Serial.println("--- HARDWARE ONLINE --- Starting handshake...");
  performHandshake();
}

// ═══════════════════════════════════════════════════════════════
void performHandshake() {
  // Servo joints: nudge +10° then return to home
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (sJoints[i].pin == -1) continue;
    sJoints[i].servo.write(constrain((int)(sJoints[i].current_deg + 90 + 10), 0, 180));
  }
  delay(400);
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (sJoints[i].pin == -1) continue;
    sJoints[i].servo.write(90); // return to home
  }
  delay(300);
  // Stepper joints: nudge 3° forward and back to confirm wiring
  long nudge = (long)(3.0f * STEPS_PER_DEG);
  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {
    stJoints[i].stepper.moveTo(nudge);
    for (int k = 0; k < 50; k++) { stJoints[i].stepper.run(); delay(8); }
    stJoints[i].stepper.moveTo(0);
    for (int k = 0; k < 50; k++) { stJoints[i].stepper.run(); delay(8); }
  }
  Serial.println("HANDSHAKE OK — Robot ready.");
}

// ═══════════════════════════════════════════════════════════════
void loop() {
  updateSerial();
  updateServos();
  updateSteppers();   // Must run every loop — non-blocking
  delay(8);             // ~125 Hz control loop
}

// ═══════════════════════════════════════════════════════════════
void updateSerial() {
  while (Serial.available() > 0) {
    String cmd = Serial.readStringUntil('\n');
    cmd.trim();
    if (cmd.length() == 0) continue;
    if (cmd == "?")    { Serial.println("PONG"); continue; }
    if (cmd == "HOME") { goHome(); continue; }
    parseCommand(cmd);
  }
}

// ═══════════════════════════════════════════════════════════════
// Command format: "<name>:<angle_deg>:<speed_pct>"
void parseCommand(const String& cmd) {
  int first = cmd.indexOf(':');
  int last  = cmd.lastIndexOf(':');
  if (first < 1 || last <= first) {
    Serial.print("ERR: Malformed cmd: "); Serial.println(cmd);
    return;
  }

  String name  = cmd.substring(0, first);
  float  angle = cmd.substring(first + 1, last).toFloat();
  float  spd   = cmd.substring(last  + 1).toFloat();

  // Search servo joints
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (name.equalsIgnoreCase(sJoints[i].name)) {
      // Clamp to joint software limits
      angle = constrain(angle, sJoints[i].min_limit, sJoints[i].max_limit);
      sJoints[i].target_deg = angle;
      sJoints[i].speed_pct  = constrain(spd, 0.0f, 100.0f);
      Serial.print("ACK[SERVO] "); Serial.print(sJoints[i].name);
      Serial.print(" -> "); Serial.print(angle); Serial.println(" deg");
      return;
    }
  }

  // Search stepper joints
  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {
    if (name.equalsIgnoreCase(stJoints[i].name)) {
      angle = constrain(angle, stJoints[i].min_limit, stJoints[i].max_limit);
      stJoints[i].target_deg = angle;
      stJoints[i].speed_pct  = constrain(spd, 0.0f, 100.0f);
      long   steps   = (long)(angle * STEPS_PER_DEG);
      float  sps     = (stJoints[i].speed_pct / 100.0f) * MAX_SPEED_SPS;
      if (sps < 50.0f) sps = 50.0f;  // minimum speed guard
      stJoints[i].stepper.setMaxSpeed(sps);
      stJoints[i].stepper.moveTo(steps);
      Serial.print("ACK[STEP] "); Serial.print(stJoints[i].name);
      Serial.print(" -> "); Serial.print(angle);
      Serial.print(" deg | "); Serial.print(steps);
      Serial.println(" steps");
      return;
    }
  }

  Serial.print("ERR: Unknown joint '"); Serial.print(name); Serial.println("'");
}

// ═══════════════════════════════════════════════════════════════
// Move all joints to home (0 degrees)
void goHome() {
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    sJoints[i].target_deg = 0.0f;
  }
  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {
    stJoints[i].target_deg = 0.0f;
    float home_sps = (stJoints[i].speed_pct / 100.0f) * MAX_SPEED_SPS;
    if (home_sps < 50.0f) home_sps = 50.0f;
    stJoints[i].stepper.setMaxSpeed(home_sps);
    stJoints[i].stepper.moveTo(0);
  }
  Serial.println("HOME: All joints returning to 0 deg.");
}

// ═══════════════════════════════════════════════════════════════
// Smooth servo interpolation (runs every 8 ms)
void updateServos() {
  for (int i = 0; i < NUM_SERVO_JOINTS; i++) {
    if (sJoints[i].pin == -1) continue;
    float cur = sJoints[i].current_deg;
    float tgt = sJoints[i].target_deg;
    float err = tgt - cur;
    if (fabsf(err) < 0.1f) {
      sJoints[i].current_deg = tgt;        // snap to target
    } else {
      // Speed_pct ∈ [0,100] → step ∈ [0.08, 8] deg per tick
      float step = (sJoints[i].speed_pct / 100.0f) * 8.0f;
      if (step < 0.08f) step = 0.08f;
      sJoints[i].current_deg += (err > 0) ? step : -step;
      // Overshoot guard
      if ((err > 0 && sJoints[i].current_deg > tgt) ||
          (err < 0 && sJoints[i].current_deg < tgt))
        sJoints[i].current_deg = tgt;
    }
    // Map robot degrees [-180,+180] → servo [0,180]
    //   robot 0° → servo 90° (midpoint)
    int sv = (int)constrain(sJoints[i].current_deg + 90.0f, 0.0f, 180.0f);
    sJoints[i].servo.write(sv);
  }
}

// ═══════════════════════════════════════════════════════════════
// Non-blocking AccelStepper tick — MUST be called every loop iter
void updateSteppers() {
  for (int i = 0; i < NUM_STEPPER_JOINTS; i++) {
    stJoints[i].stepper.run();
  }
}
